Testing the PR
trytocloud/java-racingcar pull request #1
Opened 2018-01-24 00:51 UTC by jyterencekim

2018-01-25 13:33 UTC, trytocloud requested changes
리뷰 연습!

아래 코드 참고해서 테스트 코드 작성해보아요.
https://github.com/trytocloud/java-racingcar/blob/step1/src/test/java/racing/MoverTest.java

2018-01-25 13:33 UTC, trytocloud commented on src/test/java/racingcar/TestRunner.java
> +   public static void main(String[] args) {
main 함수 대신에 `@Test` 만 사용해서 테스트 해보면 어떨까?
Run as -> Junit Test 써보기

2018-01-25 13:33 UTC, trytocloud commented on src/test/java/racingcar/TestJUnit.java
> +		assertEquals("working fine", str);
추가로 assert로 검증할만한 건 없을까?
4번 앞으로 가기로 결정되었다면, 정말로 4번 움직일까?

2018-01-25 13:33 UTC, trytocloud commented on src/main/java/racingcar/RacingGame.java
> +	private ArrayList<Car> carList = new ArrayList<Car>();
List 인터페이스를 사용하도록 바꿔보기

2018-01-25 13:33 UTC, trytocloud commented on src/main/java/racingcar/Car.java
> +//import java.util.Random;
불필요한 주석 삭제하기

2018-01-25 13:33 UTC, trytocloud commented on src/main/java/racingcar/Car.java
> +	private static boolean isToMove() {
non-static으로 바꿔보면 어떨까?

2018-01-25 18:58 UTC, jyterencekim commented on src/main/java/racingcar/RacingCar.java
> +		numberTrials = inputGameConfiguration[1];
요런 부분은 보통 어떻게 처리해?

2018-01-25 18:58 UTC, jyterencekim commented on src/test/java/racingcar/TestRunner.java
> +   public static void main(String[] args) {
오키오키!

2018-01-25 18:59 UTC, jyterencekim commented on src/test/java/racingcar/TestJUnit.java
> +		assertEquals("working fine", str);
오키오키!

2018-01-26 01:34 UTC, trytocloud commented on src/main/java/racingcar/RacingCar.java
> +		numberTrials = inputGameConfiguration[1];
배열보다는 객체로 만들어주기 :) 그렇게 해서 명시적으로 가져오기

2018-01-26 15:45 UTC, trytocloud commented on src/main/java/racingcar/RacingCar.java
> +		numberTrials = inputGameConfiguration[1];
0, 1 인덱스로 두다가 요구 사항이 바뀌어서 다른 것이 추가되면 모호해질 거야. 버그도 양산! ㅋㅋ

2018-01-27 12:07 UTC, closed without merging